version: "3.8"

services:
  node:
    image: node
    working_dir: /web
    volumes:
      - ./web:/web:rw
    entrypoint: "/bin/bash"

  web:
    image: nginx
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - 14001:80

  wasm:
    build:
      context: wasm
      dockerfile: Dockerfile
    working_dir: /mnt/src
    volumes:
      - ./wasm:/mnt/wasm
      - ./src:/mnt/src
    

